### ISSUE TITLE
Microsoft Edge support

### ISSUE THREAD

**Issue by jacobnbrum** [ghinda/css-toggle-switch#62] opened 2019-01-09 22:27 UTC
Hi,
I have been running into an issue while trying to get this to work in the Microsoft Edge browser. The switch appears to display correctly, but clicking on it does not seem to trigger any action.

Any ideas about this?

Here is the HTML for the related element:
`<label class="switch-light switch-candy" style="width:90px;" onclick="">
    <input name="test_switch" type="hidden" value="0"><input style="" type="checkbox" value="1" name="test_switch" id="test_switch">
                  <span>
                    <span>No</span>
                    <span>Yes</span>
                    <a></a>
                  </span>
                </label>`

Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134

**Comment by ghinda** [comment] 2019-01-10 10:55
I can't replicate the issue you're having. Maybe you have other scripts/styles on the page that are interacting with the elements?

This is the demo I tested in the latest Edge (it includes your code):
[edge-demo](https://www.siloz.io/#s=N4IgbgpgTgzglgewHYgFwEYA0IBmcA2EMaA2qAC4CeADhGiABbkC2+I2AxsuREufQB58AQwBGEfAAIOImDAC8AHRAwA7nHIcGAWnxwA5k0lqNW7R2FIAJpWXGqhJSHVXyDVAE4ADNQAeAbjtkGTgOAGsnZQA+SQE4JGoAV3JJJGFmCCceGHIAfRNNBjsqWicGOCsrXjswYXxEzOUvaLiE5PtKR2VimkaQLQhw0QRfGrqGp3Q7NIysojyCrTsKuZz89ULo2JhqSxiBHb2AOQQBAHpDpH3LqIBNInOb2OEo85fYi92rj5FxfCjFEhAUJ4mFJFAJE4cp0iAwIBByD1SsoeL5yGcOHI7AwITgyuRyNQYKgzhirEgAHQAKxgVT0YCgFKQCLOCWYGLk2nICH0+kI2kWDAAAiJsuirHAcmdubz+YKKZiYHYzgCgSgAL6YCi9eiK9j9bi8fioEAgTXa2j0Gn6rh8I30M0AXWw1Hq+nixFQJGdIDcEAy9BgCBEUDgAC8IFZJHpDPwXZYiGhQNbUKBypVeGhyFAGpr+nIk4wKlUUKhs7nsExWEn1bWgA)

**Comment by jacobnbrum** [comment] 2019-01-10 16:14
**Thank you so much for looking into this. I really like this project.**
I just tried your demo and it did not work on a couple of Edge browsers I tried. The browsers are slightly out of date, so I will try and update them and see if that resolves the issue.

**Comment by ghinda** [comment] 2019-01-10 16:15
Cool. Closing this for now. Will reopen if the issue still happens.

**Closed by ghinda** 2019-01-10 16:15 UTC

**Comment by jacobnbrum** [comment] 2019-01-10 16:35
I just tried the demo in a couple of other places including an up to date Edge browser and a much older version of Edge.

Do you have any ideas of what else I could look into?


![switch-toggle-edge-gif](https://user-images.githubusercontent.com/9966112/50982597-87286980-14cb-11e9-95a5-93185e8d2872.gif)


Thanks again.

**Comment by ghinda** [comment] 2019-01-10 16:57
I managed to reproduce the issue in Edge 17. Seems to be fixed in Edge 18.

To also fix it in `17`, remove the first `hidden` input you have inside the label:
[fixed-edge-demo](https://www.siloz.io/#s=N4IgbgpgTgzglgewHYgFwEYA0IBmcA2EMaA2qAC4CeADhGiABbkC2+I2AxsuREufQB58AQwBGEfAAIOImDAC8AHRAwA7nHIcGAWnxwA5k0lqNW7R2FIAJpWXGqhJSHVXyDVAE4ADNQAeAbjtkGTgOAGsnZQA+RSRJSQEAQm1tSQAlAFEAWQB5ADUMyQAJAEkAETKMgDlJEqqABQBVABVY+IE4JGoAV3JJJGFmCCceGHIAfRNNBjsqWicGOCsrXjswYXxu4eUvaLbJFJi4hM6evrHKR2VZmm2QLQhw0QRfNY2tp3Q7AaGRogmplo7Es-mNJuppntjvsBDBqJYogk4QiqggBAB6ZFIRGw+HYgCaRAxWJxwiiGLJCUxeKOGJE4nwR1iQk6YUkUAkTguhBgDAgEHIN3myh4vnI6I4cjsDA5OAW5HI1BgqHREqsSAAdAArGArPRgKAapAC9FdZgSuTacgIfT6QjaQEMAACIlG4qscDG6Ottvtjo1kpgdnRTJQAF9MBRbvRA+x7txePxUCAQBGo7R6Dq41w+In6KmALrYaibfSdYioEhFkBuCBDegwBAiKBwABeECskj0hn4xcsRDQoCzqFAi2WvDQ5CgWwj9zkg8YSxWKFQU5n2CYrEHYZ3QA)

It seems Edge 17 tries to focus the hidden input when clicking the label, causing the issue.

**Comment by jacobnbrum** [comment] 2019-01-10 17:05
It looks like my projects framework was generating that hidden file.

Thank you so much, I really appreciate it!
